import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { getProjectById } from '../api/modules/projectsApi'
import * as weekly from '../api/modules/weeklyUpdatesApi'
import * as achievement from '../api/modules/achievementsApi'
import * as risk from '../api/modules/risksApi'
import * as blocker from '../api/modules/blockersApi'
import * as customer from '../api/modules/customerConnectsApi'
import { unwrap } from '../api/apiResponse'
import { useApi } from '../hooks/useApi'
import DataTable from '../components/common/DataTable'
import ConfirmModal from '../components/common/ConfirmModal'
import FormField from '../components/common/FormField'
import { Feedback, Loading } from '../components/common/Feedback'
import { enums } from '../constants/enums'

const resourceConfigs = [
  { key: 'weeklyUpdates', label: 'Weekly updates', idKey: 'weeklyUpdateId', api: weekly, createFields: [{ name: 'userId', label: 'User ID', type: 'number', required: true }, { name: 'reportingWeek', label: 'Reporting week', required: true }, { name: 'completedActivities', label: 'Completed activities', type: 'textarea', required: true }, { name: 'plannedActivities', label: 'Planned activities', type: 'textarea', required: true }, { name: 'progressUpdate', label: 'Progress update', type: 'textarea', required: true }], updateFields: [{ name: 'completedActivities', label: 'Completed activities', type: 'textarea', required: true }, { name: 'plannedActivities', label: 'Planned activities', type: 'textarea', required: true }, { name: 'progressUpdate', label: 'Progress update', type: 'textarea', required: true }], columns: [{ key: 'weeklyUpdateId', label: 'ID' }, { key: 'reportingWeek', label: 'Week' }, { key: 'userName', label: 'Owner' }, { key: 'status', label: 'Status' }], list: 'getProjectUpdates', create: 'createWeeklyUpdate', update: 'updateWeeklyUpdate', remove: 'deleteWeeklyUpdate' },
  { key: 'achievements', label: 'Achievements', idKey: 'achievementId', api: achievement, createFields: [{ name: 'weeklyUpdateId', label: 'Weekly update ID', type: 'number' }, { name: 'title', label: 'Title', required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'businessImpact', label: 'Business impact', type: 'textarea', required: true }], updateFields: [{ name: 'title', label: 'Title', required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'businessImpact', label: 'Business impact', type: 'textarea', required: true }], columns: [{ key: 'achievementId', label: 'ID' }, { key: 'title', label: 'Title' }, { key: 'businessImpact', label: 'Business impact' }], list: 'getProjectAchievements', create: 'createAchievement', update: 'updateAchievement', remove: 'deleteAchievement' },
  { key: 'risks', label: 'Risks', idKey: 'riskId', api: risk, createFields: [{ name: 'title', label: 'Title', required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'riskType', label: 'Risk type', options: enums.riskType, required: true }, { name: 'severity', label: 'Severity', options: enums.riskSeverity, required: true }, { name: 'probability', label: 'Probability', type: 'number', required: true }, { name: 'impact', label: 'Impact', type: 'number', required: true }, { name: 'ownerUserId', label: 'Owner user ID', type: 'number', required: true }, { name: 'mitigationPlan', label: 'Mitigation plan', type: 'textarea', required: true }, { name: 'targetDate', label: 'Target date', type: 'date', required: true }], updateFields: [{ name: 'title', label: 'Title', required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'severity', label: 'Severity', options: enums.riskSeverity, required: true }, { name: 'riskStatus', label: 'Risk status', options: enums.riskStatus, required: true }, { name: 'probability', label: 'Probability', type: 'number', required: true }, { name: 'impact', label: 'Impact', type: 'number', required: true }, { name: 'mitigationPlan', label: 'Mitigation plan', type: 'textarea', required: true }, { name: 'targetDate', label: 'Target date', type: 'date', required: true }], columns: [{ key: 'riskId', label: 'ID' }, { key: 'title', label: 'Risk' }, { key: 'riskType', label: 'Type' }, { key: 'severity', label: 'Severity' }, { key: 'riskStatus', label: 'Status' }, { key: 'riskScore', label: 'Score' }], list: 'getProjectRisks', create: 'createRisk', update: 'updateRisk', remove: 'deleteRisk' },
  { key: 'blockers', label: 'Blockers', idKey: 'blockerId', api: blocker, createFields: [{ name: 'ownerUserId', label: 'Owner user ID', type: 'number', required: true }, { name: 'severity', label: 'Severity', options: enums.blockerSeverity, required: true }, { name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'raisedDate', label: 'Raised date', type: 'date', required: true }, { name: 'targetResolutionDate', label: 'Target resolution date', type: 'date', required: true }], updateFields: [{ name: 'description', label: 'Description', type: 'textarea', required: true }, { name: 'status', label: 'Status', options: enums.blockerStatus, required: true }, { name: 'targetResolutionDate', label: 'Target resolution date', type: 'date', required: true }], columns: [{ key: 'blockerId', label: 'ID' }, { key: 'description', label: 'Blocker' }, { key: 'severity', label: 'Severity' }, { key: 'status', label: 'Status' }, { key: 'ownerName', label: 'Owner' }], list: 'getProjectBlockers', create: 'createBlocker', update: 'updateBlocker', remove: 'deleteBlocker' },
  { key: 'customerConnects', label: 'Customer connects', idKey: 'customerConnectId', api: customer, createFields: [{ name: 'lastMeetingDate', label: 'Last meeting date', type: 'date', required: true }, { name: 'nextMeetingDate', label: 'Next meeting date', type: 'date', required: true }, { name: 'meetingFrequency', label: 'Meeting frequency', options: enums.customerConnectFrequency, required: true }, { name: 'customerFeedback', label: 'Customer feedback', type: 'textarea', required: true }, { name: 'escalationRaised', label: 'Escalation raised', type: 'boolean', options: ['true', 'false'], required: true }], updateFields: [{ name: 'nextMeetingDate', label: 'Next meeting date', type: 'date', required: true }, { name: 'meetingFrequency', label: 'Meeting frequency', options: enums.customerConnectFrequency, required: true }, { name: 'customerFeedback', label: 'Customer feedback', type: 'textarea', required: true }, { name: 'escalationRaised', label: 'Escalation raised', type: 'boolean', options: ['true', 'false'], required: true }], columns: [{ key: 'customerConnectId', label: 'ID' }, { key: 'lastMeetingDate', label: 'Last meeting' }, { key: 'nextMeetingDate', label: 'Next meeting' }, { key: 'meetingFrequency', label: 'Frequency' }, { key: 'escalationRaised', label: 'Escalation' }], list: 'getProjectCustomerConnects', create: 'createCustomerConnect', update: 'updateCustomerConnect', remove: 'deleteCustomerConnect' },
]

function ProjectResource({ projectId, config }) {
  const request = useApi(); const [rows, setRows] = useState([]); const [editor, setEditor] = useState(null); const [remove, setRemove] = useState(null)
  const load = () => request.run(() => config.api[config.list](projectId), `Loaded ${config.label.toLowerCase()}`).then(({ response }) => setRows(unwrap(response) || [])).catch(() => {})
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(load, [projectId])
  const fieldValue = (field, event) => field.type === 'number' ? Number(event.target.value) : event.target.value
  const submit = async (event) => { event.preventDefault(); const fields = editor.mode === 'create' ? config.createFields : config.updateFields; const payload = Object.fromEntries(fields.map(({ name, type }) => [name, type === 'boolean' ? editor.values[name] === 'true' : editor.values[name] ?? ''])); if (editor.mode === 'create') payload.projectId = Number(projectId); try { await request.run(() => editor.mode === 'create' ? config.api[config.create](payload) : config.api[config.update](editor.values[config.idKey], payload), `${config.label} saved`); setEditor(null); load() } catch { /* feedback is rendered below */ } }
  const destroy = async () => { try { await request.run(() => config.api[config.remove](remove[config.idKey]), `${config.label} deleted`); setRemove(null); load() } catch { /* feedback is rendered below */ } }
  return <div className="card border-0 shadow-sm"><div className="card-header bg-white d-flex justify-content-between align-items-center"><h2 className="h5 mb-0">{config.label}</h2><button className="btn btn-sm btn-primary" onClick={() => setEditor({ mode: 'create', values: {} })}>Add</button></div><DataTable columns={config.columns} rows={rows} loading={request.loading && !editor && !remove} emptyMessage={`No ${config.label.toLowerCase()} recorded.`} actions={(row) => <><button className="btn btn-sm btn-outline-primary me-2" onClick={() => setEditor({ mode: 'edit', values: row })}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={() => setRemove(row)}>Delete</button></>} />{editor && <div className="modal d-block" role="dialog" aria-modal="true"><div className="modal-dialog modal-lg modal-dialog-centered"><form className="modal-content" onSubmit={submit}><div className="modal-header"><h3 className="modal-title fs-5">{editor.mode === 'create' ? `Add ${config.label}` : `Edit ${config.label}`}</h3><button type="button" className="btn-close" onClick={() => setEditor(null)} aria-label="Close" /></div><div className="modal-body row">{(editor.mode === 'create' ? config.createFields : config.updateFields).map((field) => <div className="col-md-6" key={field.name}><FormField {...field} value={editor.values[field.name]} onChange={(event) => setEditor({ ...editor, values: { ...editor.values, [field.name]: fieldValue(field, event) } })} /></div>)}</div><div className="modal-footer"><button type="button" className="btn btn-outline-secondary" onClick={() => setEditor(null)}>Cancel</button><button className="btn btn-primary" disabled={request.loading}>Save</button></div></form></div></div>}<ConfirmModal open={Boolean(remove)} title={`Delete ${config.label}`} message={`Delete this ${config.label.toLowerCase().replace(/s$/, '')}?`} onCancel={() => setRemove(null)} onConfirm={destroy} loading={request.loading} /><div className="px-3"><Feedback error={request.error} success={request.success} /></div></div>
}

export default function ProjectWorkspacePage() {
  const { projectId } = useParams(); const request = useApi(); const [project, setProject] = useState(null)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { request.run(() => getProjectById(projectId)).then(({ response }) => setProject(unwrap(response))).catch(() => {}) }, [projectId])
  if (request.loading && !project) return <Loading />
  return <section><div className="mb-4"><p className="eyebrow mb-1">Project workspace</p><h1 className="h2 mb-1">{project?.projectName || 'Project'}</h1><p className="text-secondary">{project?.projectCode} · {project?.clientName} · {project?.projectStatus}</p><Feedback error={request.error} /></div><div className="row g-4">{resourceConfigs.map((config) => <div className="col-12" key={config.key}><ProjectResource projectId={projectId} config={config} /></div>)}</div></section>
}
