import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import * as api from '../api/modules/wsrReportsApi'
import { pageOf } from '../api/apiResponse'
import { useApi } from '../hooks/useApi'
import { usePagination } from '../hooks/usePagination'
import DataTable from '../components/common/DataTable'
import Pagination from '../components/common/Pagination'
import FormField from '../components/common/FormField'
import UserSelect from '../components/common/UserSelect'
import { Feedback } from '../components/common/Feedback'
import { can } from '../constants/permissions'
import { getSession } from '../utils/authUtils'

export default function WsrReportsPage() {
  const request = useApi(); const { page, pageSize, setPage } = usePagination(); const [rows, setRows] = useState([]); const [meta, setMeta] = useState({}); const [creating, setCreating] = useState(false); const [form, setForm] = useState({ projectId: '', submittedBy: '', reportingWeek: '' }); const role = getSession().role; const canSubmit = can(role, 'wsr', 'submit'); const canApprove = can(role, 'wsr', 'approve')
  const load = () => request.run(() => api.getAllReports({ page, size: pageSize, sortBy: 'wsrReportId' })).then(({ response }) => { const result = pageOf(response); setRows(result.content); setMeta(result) }).catch(() => {})
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [page])
  const create = async (event) => { event.preventDefault(); try { await request.run(() => api.createReport({ projectId: Number(form.projectId), submittedBy: Number(form.submittedBy), reportingWeek: form.reportingWeek }), 'Report created'); setCreating(false); setForm({ projectId: '', submittedBy: '', reportingWeek: '' }); load() } catch { /* feedback is rendered below */ } }
  const lifecycle = async (action, row) => { const approverId = action === 'submit' ? null : Number(window.prompt('Approver user ID')); if (action !== 'submit' && !approverId) return; const comments = action === 'reject' ? window.prompt('Rejection comments') || '' : null; const verb = action === 'submit' ? 'submitted' : action === 'approve' ? 'approved' : 'rejected'; try { await request.run(() => action === 'submit' ? api.submitReport(row.wsrReportId) : action === 'approve' ? api.approveReport(row.wsrReportId, approverId) : api.rejectReport(row.wsrReportId, approverId, comments), `Report ${verb}`); load() } catch { /* feedback is rendered below */ } }
  return <section><div className="d-flex flex-wrap gap-3 justify-content-between align-items-start mb-4"><div><p className="eyebrow mb-1">Reporting</p><h1 className="h2 mb-1">WSR reports</h1><p className="text-secondary">Review submission status and manage the report approval lifecycle.</p></div>{canSubmit && <button className="btn btn-primary" onClick={() => setCreating(!creating)}>{creating ? 'Close form' : 'Create report'}</button>}</div><Feedback error={request.error} success={request.success} />{creating && <form className="card border-0 shadow-sm p-4 mb-4 row" onSubmit={create}><div className="col-md-4"><FormField label="Project ID" name="projectId" type="number" value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })} required /></div><div className="col-md-4"><UserSelect label="Submitted by" name="submittedBy" value={form.submittedBy} onChange={(e) => setForm({ ...form, submittedBy: e.target.value })} required /></div><div className="col-md-4"><FormField label="Reporting week" name="reportingWeek" type="date" value={form.reportingWeek} onChange={(e) => setForm({ ...form, reportingWeek: e.target.value })} required /></div><div><button className="btn btn-primary" disabled={request.loading}>Create report</button></div></form>}<div className="card border-0 shadow-sm"><DataTable columns={[{ key: 'wsrReportId', label: 'ID' }, { key: 'projectName', label: 'Project' }, { key: 'reportingWeek', label: 'Reporting week' }, { key: 'status', label: 'Status' }, { key: 'submittedBy', label: 'Submitted by' }, { key: 'submissionDate', label: 'Submitted' }]} rows={rows} loading={request.loading && !creating} emptyMessage="No WSR reports found." actions={(row) => <div className="d-flex flex-wrap gap-2"><Link className="btn btn-sm btn-outline-primary" to={`/wsr-reports/${row.wsrReportId}/details`}>Details</Link>{canSubmit && row.status === 'DRAFT' && <button className="btn btn-sm btn-outline-secondary" onClick={() => lifecycle('submit', row)}>Submit</button>}{canApprove && row.status === 'SUBMITTED' && <><button className="btn btn-sm btn-outline-success" onClick={() => lifecycle('approve', row)}>Approve</button><button className="btn btn-sm btn-outline-danger" onClick={() => lifecycle('reject', row)}>Reject</button></>}</div>} /></div><div className="mt-3"><Pagination page={page} totalPages={meta.totalPages || 0} onChange={setPage} /></div></section>
}
